info:
  title: Onion Api
  version: '1.0'
openapi: 3.0.0
components:
  schemas:
    Domain:
      type: object
      properties:
        challengeId:
          type: string
          format: uuid
        goal:
          type: string
        user:
          type: string
        friend:
          type: string
        challengeDate:
          type: string
        money:
          type: string
    ApiError:
      type: object
      properties:
        exceptionId:
          type: string
        error:
          type: string
        message:
          type: string
paths:
  /domain:
    get:
      summary: Returns challenge 
      parameters:
      - name: challengeId
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
        '400':
          $ref: '#/components/schemas/ApiError'
    post:
      summary: Creates a new challenge.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Domain'
      responses:
        '201':
          description: Created
        '400':
          $ref: '#/components/schemas/ApiError'